config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'

  resources :flights
  resources :airports
  resources :bookings, only: [:new, :create, :show]

  
  get '/search', to: 'flights#index'
end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :departing_flights, class_name: "Flight", foreign_key: "from_airport_id"
    has_many :arriving_flights, class_name: "Flight", foreign_key: "to_airport_id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  belongs_to :passenger

  accepts_nested_attributes_for :passenger, allow_destroy: true
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :from_airport, class_name: "Airport"
    belongs_to :to_airport, class_name: "Airport"
    has_many :bookings
    has_many :passengers, through: :bookings


    def flight_date_formatted
        self.start.strftime("%m/%d/%Y")
    end

    def self.search(search_params)
        search_params[:passengers] = ""
        valid_params = search_params.select{ |key,value| value != ""}
        valid_params[:start] = valid_params[:start].to_time.all_day unless valid_params[:start].nil?          
        where(valid_params)
        #search_params[:start] = search_params[:start].to_time.all_day
        #where(from_airport_id: search_params[:from_airport_id], to_airport_id: search_params[:to_airport_id],
        #start: search_params[:start])
    end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
    has_many :bookings
    has_many :flights, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    def new 
        @booking = Booking.new
        @flight = Flight.find(params[:booking])
        @num_passengers = params[:passengers].to_i
        #@passenger = []
        #@num_passengers.times do 
            #@passenger << Passenger.new
        #end
        @num_passengers.times { @booking.build_passenger }       
    end

    def create
        @booking = Booking.new(booking_params) 
        if @booking.save
            PassengerMailer.with(booking: @booking).thanks_email.deliver_now
            redirect_to @booking
        else
            @flight = Flight.find(params[:booking][:flight_id])
            render 'new'
        end
    end

    def show 
        @booking = Booking.find(params[:id])
    end

    private

    def booking_params
        params.require(:booking).permit(:flight_id, :passenger_attributes => [:id, :name, :email])
    end

    def passenger_params
        params.require(:passenger).permit( :passenger_attributes => [:id, :name, :email])
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
    def index
        @airport_option = Airport.all.map{ |u| [ u.name, u.id ] }
        @passenger_option = [1, 2, 3, 4]
        @date_option = Flight.order('start ASC').map{ |x| [x.flight_date_formatted, x.start] }
        @results = params[:flight] ? Flight.search(search_params) : Flight.all
    end

    private

    def search_params
      params.require(:flight).permit(:from_airport_id, :to_airport_id, :start, :passengers)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
    <%= f.hidden_field(:flight_id, :value => @flight.id) %>
    <% @num_passengers.times do %>
        <%= f.fields_for :passenger do |x| %>
            <%= x.label :name %>
            <%= x.text_field :name %>
            <%= x.label :email %>
            <%= x.email_field :email %><br>
        <% end %>
    <% end %>
    <%= f.submit 'Submit booking' %>
<% end %>

app/views/bookings/new.html.erb
<h1>Your booking form</h1>

<h5>From: <%= @flight.from_airport.name %> '<%= @flight.from_airport.code %>' | To: <%= @flight.to_airport.name %> '<%= @flight.to_airport.code %>' | Date: <%= @flight.start %> | Duration: <%= @flight.duration %> minutes | Passengers: <%= @num_passengers %> </h5>

<%= render 'form' %>
<%= link_to 'Back to Search', root_url %>

app/views/bookings/show.html.erb
<h1>Your Booking</h1>

<h5>From: <%= @booking.flight.from_airport.name %> '<%= @booking.flight.from_airport.code %>' | To: <%= @booking.flight.to_airport.name %> '<%= @booking.flight.to_airport.code %>' | Date: <%= @booking.flight.start %> | Duration: <%= @booking.flight.duration %> minutes </h5>

<h5><%= @booking.passenger.name %> | <%= @booking.passenger.email %></h5>

<%= link_to 'back to booking', new_booking_path %> | 
<%= link_to 'back to search', root_path %>

app/views/flights/_display.html.erb
<% if @results.none? %>
    <h3>No Results Found</h3>
<% else %>
    <ul>
    <% @results.each do |result| %>
        <li><%= form_with model: @booking, url: new_booking_path, method: :get, local: true do |f| %>
         <%= f.radio_button :booking, result.id  %>
        From: <%= result.from_airport.name %> '<%= result.from_airport.code %>' | To: <%= result.to_airport.name %> '<%= result.to_airport.code %>' | Date: <%= result.start %> | Duration: <%= result.duration %> minutes 
        <%= f.hidden_field(:passengers, :value => params[:flight] ? params[:flight][:passengers] : '0') %>
        <%= f.submit 'Select Flight' %>
        <% end %></li>
    <% end %>
    </ul>
<% end %>

app/views/flights/_search.html.erb
<% if false %>
<%= form_tag(search_path, :method => "get") do %> 
    <%= label_tag(:from_airport_id, "Choose deperture:") %>     
    <%= select_tag(:from_airport_id, options_for_select(@airport_option)) %>
    <%= label_tag(:to_airport_id, "Choose destination:") %>  
    <%= select_tag(:to_airport_id, options_for_select(@airport_option), include_blank: true) %></br>
    <%= label_tag(:passengers, "Number of passengers:") %>
    <%= select_tag(:passengers, options_for_select(@passenger_option), include_blank: true) %></br>
    <%= label_tag(:start, "Choose date:") %>
    <%= select_tag(:start, options_for_select(@date_option), include_blank: true) %></br>  
    <%= button_tag "Search",:name => nil %>       
<% end %>
<% end %>

<%= form_with(scope: :flight, method: :get, local: true) do |f| %>
    <%= f.label :from %>
    <%= f.select :from_airport_id, options_for_select(@airport_option), include_blank: true %>

    <%= f.label :to %>
    <%= f.select :to_airport_id, options_for_select(@airport_option), include_blank: true %>

    <%= f.label :passengers, "Number of passengers" %>
    <%= f.select :passengers, options_for_select(@passenger_option), include_blank: true %>

    <%= f.label :start, "Flight date" %>
    <%= f.select :start, options_for_select(@date_option), include_blank: true %></br></br>

    <%= f.submit "Search" %>
<% end %>

app/views/flights/index.html.erb
<h1>Search your flight</h1>

<%= render 'search' %>

<br>
<br>
<h1>Flights found</h1>

<%= render 'display' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/passengers/_passenger.html.erb
<%= passenger.name %>
<%= passenger.email %>

app/views/passengers/_passengers.html.erb
<%= passenger.name %>
<%= passenger.email %>